clients/urls.py
from .views import CreateClientView
from django.urls import path

app_name = 'clients'

urlpatterns = [
   path('createclient/', CreateClientView.as_view(), name='client_create'),
]

estimates/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    EstimateListView,
    EstimateFormView,
    EstimateUpdateView,
    AddPositionsFormView,
    CloseEstimateView,
    EstimateDeleteView,
    EstimatePositionDeleteView,
    estimate_pdf_print,
)

app_name = 'estimates'

urlpatterns = [
    path('', login_required(EstimateListView.as_view()), name='main'),
    path('new/',login_required(EstimateFormView.as_view()), name="estimate"),
    path('<pk>/', login_required(AddPositionsFormView.as_view()), name='estimate_detail'),
    path('<pk>/close/', login_required(CloseEstimateView.as_view()), name='close'),
    path('<pk>/update/', login_required(EstimateUpdateView.as_view()), name='estimate-update'),
    path('<pk>/delete/', login_required(EstimateDeleteView.as_view()), name='estimate-delete'),
    path('<pk>/pdf/', login_required(estimate_pdf_print), name="pdf"),
    path('<pk>/delete/<int:position_pk>/', login_required(EstimatePositionDeleteView.as_view()), name='position-delete'),
]

invoice_app/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    InvoiceListView,
    InvoiceFormView,
    InvoiceUpdateView,
    InvoiceUpdateView,
    AddPositionsFormView,
    CloseInvoiceView,
    InvoiceDeleteView,
    InvoicePositionDeleteView,
    PayedInvoiceView,
    invoices_pdf_print,

    
)


app_name = 'invoice_app'

urlpatterns = [
    path('', login_required(InvoiceListView.as_view()), name='main'),
    path('new/', login_required(InvoiceFormView.as_view()), name="create"),
    path('<pk>/', login_required(AddPositionsFormView.as_view()), name='detail'),
    path('<pk>/close/', login_required(CloseInvoiceView.as_view()), name='close'),
    path('<pk>/payed/', login_required(PayedInvoiceView.as_view()), name='payed'),
    path('<pk>/update/', login_required(InvoiceUpdateView.as_view()), name='update'),
    path('<pk>/pdf/', login_required(invoices_pdf_print), name="pdf"),
    path('<pk>/delete/', login_required(InvoiceDeleteView.as_view()), name='invoice-delete'),
    path('<pk>/delete/<int:position_pk>/', login_required(InvoicePositionDeleteView.as_view()), name='position-delete'),
    
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from invoice_app .views import dashboard
from profiles.views import login_view
from estimates.views import EstimateFormView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='account_login'),
    path('',dashboard, name='profile_view'),
    path('positions/', include('positions.urls', namespace ='positions')),
    path('invoice_app/', include('invoice_app.urls', namespace ='invoice_app')),
    path('estimates/', include('estimates.urls', namespace ='estimates')),
    path('clients/', include('clients.urls', namespace='clients')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/',include('allauth.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls'))
]

urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Veedata Invoice panel"
admin.site.index_title = "Veedata Invoice Management"

positions/urls.py
from django.urls import path, include
from dash_apps.account import index
from django.contrib.auth.decorators import login_required
from .views import (
invoice_analytics,
analytics_routes,
InvoiceAnalyticView,
payed_invoice)

from dash_apps import (
invoice_plots,
payed_plot)
app_name = 'positions'

urlpatterns = [
    path('analytics/',login_required(invoice_analytics), name='invoice_plot'),
    path('plot/',login_required(InvoiceAnalyticView.as_view()), name='plot'),
    path('payed/',login_required(payed_invoice), name='payed'),
    path('pychart/', login_required(index), name='pychart'),
    path('routes/',login_required(analytics_routes), name='routing')
]

templates/invoice/create.html
{% extends 'partials/base.html' %}

{% load crispy_forms_tags %}

{% block title %}
  <h3>create a new Invoice </h3> 
{% endblock title %}

{% block content %}
   <a href="{% url 'clients:client_create' %}" class ="btn btn-warning"> +add client</a>
   <form action="" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
       <button type="submit" class="btn btn-primary ">save</button>
  </form>
{% endblock content %}

templates/invoice/detail.html
{% extends 'partials/base.html' %}

{% load crispy_forms_tags %}

{% block title %}

{% endblock title %} 

{% block content %}

 
     <!--add Modal -->
    <div class="modal fade" id="addPositionsModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">add position</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
             <form action="" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <div class="modal-footer">
                  <button type="submit"  class="btn btn-secondary" value="Submit">Save changes</button>
              </form>
          </div>
          </div>
        </div>
      </div>
      </div>
      
      
      
       <!--Invoice Modal -->
       <div class="modal fade" id="closePositionsModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="staticBackdropLabel">Caution</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body">
                 Are you sure you want to close the invoice ?
                 <p>When Invoice is closed it will not be edited.</p>
               </div>
               <div class="modal-footer">
              <a href="{% url 'invoice_app:close' obj.pk %}" class="btn btn-secondary">Close</a>
             </div>
           </div>
          </div>
        </div>
      <div>
        {% if not obj.closed  %}
        <!-- Button trigger modal -->
       <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addPositionsModal">
        +add position.
       </button>
       <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#closePositionsModal">
        close positions.
       </button>
       {% else %}

      <!--Payment Modal -->
      <div class="modal fade" id="payedPositionsModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="staticBackdropLabel">Caution</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body">
                 Do you want to mark this invoice as payed ?
                 <p>once marked this cannot be undone for this Invoice.</p> 
               </div>
               <div class="modal-footer">
              <a href="{% url 'invoice_app:payed' obj.pk %}" class="btn btn-secondary">Confirm</a>
             </div>
           </div>
          </div>
        </div>
      <div>
       <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#payedPositionsModal">
        Mark as payed.
       </button>

       <a href="  {% url 'invoice_app:pdf' obj.pk %} "class="btn btn-danger">export to pdf</a>
       {% endif %}
      </div>    
    
    {% if messages %}
     {% for message in messages %}
       {% if message.tags == 'info' %}
          <div class ="alert alert-primary mt-2">
           {{message}}
        {% endif %} 
      {% endfor %}
    {% endif %}
 

   <div class= "mt-3">
      <h5>Client : {{ obj.clients.name }}</h5>
      <hr>
      <h3>Positions</h3> {{obj.clients.company_name}}</h3>
   
      {% if qs %}
      <table class="table">
        <thead>
          <tr>
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Description</th>
              <th scope="col">Qty</th>
              <th scope="col">Price</th>
              <th scope="col">Subtotal</th>
              <th scope="col">Delete</th>
              <th scope="col">Payment</th>
           </tr>
        </thead>
        <tbody>
          {% for item in qs %}
            <tr style = "vertical-align:middle;">
                <th scope="row">{{forloop.counter}}</th>
                <td>{{item.title}}</td>
                <td>{{item.description}}</td>
                <td>{{item.quantity}}</td>
                <td>R {{item.price}}</td>
                <td>R  {% widthratio item.quantity 1 item.price %} </td>
                <td>
                    {% if not obj.closed %}
                    <a href="{% url 'invoice_app:position-delete' obj.pk item.pk %}" class="btn btn-danger">x</a>
                    {% else %}
                    closed
                    {% endif %}
                </td>
                  <td>
                    {% if not obj.payed %}
                     not payed
                    {% else %}
                    payed
                    {% endif %}
                 </td>

             </tr>
            {% endfor %}
            
           </tbody>
        </table> 
        <div class="mt-2 text-end">
            <h2>Total amount: R {{ obj.total_amount}}</h2>
        </div>
        {% else %}

        <h5>No positions yet.</h>
        {% endif %}


   </div>
{% endblock content %}

templates/invoice/invoice.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <title>Invoice WonderShop</title>
<style>
  .clearfix:after {
  content: "";
  display: table;
  clear: both;
}

a {
  text-decoration: underline;
}

body {
  position: relative;
  margin: 0 auto; 
  color: #001028;
  background: #FFFFFF; 
  font-family: Arial, sans-serif; 
  font-size: 14px; 
  font-family: Arial;
}

header {
  padding: 10px 0;
  margin-bottom: 30px;
}

#logo {
  text-align: center;
  margin-bottom: 10px;
}

#logo img {
  width: 90px;
}

h1 {
  
  color: #5D6975;
  font-size: 2.4em;
  line-height: 1.4em;
  font-weight: normal;
  text-align: center;
  margin: 0 0 20px 0;
}

#project {
  float: left;
}

#project span {
  color: #5D6975;
  text-align: right;
  width: 52px;
  margin-right: 10px;
  display: inline-block;
  font-size: 14px;
}

#company {
  float: right;
  text-align: right;
}

#project div,
#company div {
  white-space: nowrap;        
}

table {
  width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
  margin-bottom: 20px;
}



table th,
table td {
  text-align: center;
}

table th {
  
  
  color: #5D6975;
  border-bottom: 1px solid #C1CED9;
  white-space: nowrap;        
  font-weight: normal;
}

table .service,
table .desc {
  text-align: left;
}

table td {
 padding-top:5px;
 padding-bottom:5px;
  
}

table tr {
  border-bottom: 1px solid #C1CED9;
}

table td.service,
table td.desc {
  vertical-align: top;
}

table td.unit,
table td.qty,
table td.total {
  font-size: 1.2em;
}

table td.grand {
  border-top: 1px solid #5D6975;;
}

#notices .notice {
  color: #5D6975;
  font-size: 1.2em;
}

footer {
  color: #5D6975;
  width: 100%;
  height: 30px;
  position: absolute;
  bottom: 0;
  border-top: 1px solid #C1CED9;
  padding: 8px 0;
  text-align: center;
}


  </style>
</head>

<body>
  <header class="clearfix">
    <div id="logo" style="display:flex; justify-content:center; align-items:center;">
      {#<img src="static/firstapp/images/logo.png" class="brand-logo" width=60 height=60>#} <!--not working-->
      {#<img src="static/logo.png" class="brand-logo" height="200px">#} <!--not working-->
      <img src="D:\Mastering Django\firstproject\firstapp\logo.png" class="brand-logo" width=60 height=60>
      <h1 class="brand-name">{{ company_name }}</h1>
    </div>
    <h1>INVOICE</h1>
    <div id="company" class="clearfix">
      <div>Seller:{{ user_company }}</div>
      <div><a href="mailto:">{{request.user.email}}</a></div>
      <div><a href="www.wondershop.in:8000">www.wondershop.in:8000</a></div>
    </div>
    <div id="project">
      <div><span>CLIENT:</span> {{name}}</div>
      <div><span>COMPANY NAME:</span> {{user company}}</a></div>
      <div><span>DATE:</span> {{date}}</div>
      <div><span>INVOICE ID:</span> {invoice}}</div>
      <div><span>ADDRESS:</span> {{address}}</div>
    </div>
    <br>
    <br>
   </header>
   <h3>Positions</h3>
    <div class="table-container" style="overflow-x:auto">
      <table class="table" style="width:100%">
          <thead>
              <tr>
                <tr style="background-cole-color:#e8e8e8">
                    <th style="text-aligne:left; width:5%">#</th>
                    <th scope="col">TITLE</th>
                    <th scope="col">DESCRITION</th>
                    <th scope="col">QUANTITY</th>
                    <th scope="col">PRICE</th>
          </thead>
          <tbody>
               {% if object.positions %}
              
              <tr>
                <td>{{ forloop.counter }}</td>
                  <td scope="row">{{position.title}}</td>
                  <td>{{ position.description }}}</td>
                  <td>{{ position.quantity }}</td>
                  <td> R {{ position.price }}</td>
                  
              </tr>
              {% endfor %}
              <tr>
                  <td scope="row"></td>
                  <td>TOTAL: </td>
                  <td>R {{amount}}</td>
                  
              </tr>
          </tbody>
      </table>

    </div>
    <p style="text-align:right; font-size:12px;">*All values are in R<p>
</body>

</html>

templates/invoice/invoice_confirm_delete.html
{% extends 'partials/base.html' %}

{% block title %}

delete

{% endblock title %}


{% block  content %}
  <form action="" method="POST">
      {% csrf_token %}
       <p>
           Are you sure you want to delete ""<b>{{ object.invoice_number}}?</b>""
          <button types="submit" class="btn btn-danger" data-loading-text>Yes</button>
        </p>

{% endblock content %}

templates/invoice/invoice_index.html
 {% extends "partials/base.html" %}

 {% block title %}


 {% endblock title %}


 {% block content %}

  {% if messages %}
     {% for message in messages %}
       {% if message.tags == 'info' %}
        <div class ="alert alert-primary mt-2">
           {{message}}
        {% endif %} 
      {% endfor %}
     {% endif %}
      
   {% if qs %}
      {% for obj in qs %}
     <div class="card mb-2" style="width:100">
       <div class="card-body">
         <h5 class="card-title">{{ obj.invoice_number}} - {{obj.client.name}}</h5>
         <div class="card-text">completion date: {{obj.completion_date}}</div>
         <div class="text-muted">Amount in R{{obj.total_amount}}</div>
         <div class="mt-2">
            <a href="  {% url 'invoice_app:detail' obj.pk %} "class="btn btn-primary">Details</a>
             {% if not obj.closed %}
             <a href="  {% url 'invoice_app:invoice-delete' obj.pk%} "class="btn btn-danger">Delete</a>
            <a href="  {% url 'invoice_app:update' obj.pk %} "class="btn btn-info">Update</a>
            {% endif %}
        </div>
      </div>
    <div>{% if page_obj.has_previous %}
     {% endif %}
     {% endfor %}
     {% else %}
      <h3> No invoices created. </h3>
    
      {% endif %}
      {% if is_paginated %}
      <nav aria-label="invoice pagination">
        <ul class="pagination">
          <li class="page-item{% if page.obj.has_previous %} {% else %} enabled {% endif %}">
            <a {% if page_obj.has_previous %}
            href="?page={{page_obj.previous_page_number}}"
          {% endif %} class="page-link" >Previous</a>
          </li>
            {% endif %} 
          {% for i in paginator.page_range  %}
          <li class="page-item {% if page_obj.number == i %} active{% endif %}">
             <a class="page-link" href="?page={{i}}">{{i}}</a>
            </li>
          {% endfor %}
          <li class="page-item{% if page.obj.has_next %} {% else %} enabled {% endif %}">
            <a {% if page_obj.has_next %}
            href="?page={{page_obj.next_page_number}}"
          {% endif %} class="page-link" >Next</a> 
        </ul>
      </nav>
      


 {% endblock content %}

templates/invoice/pdf_print.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <title>Invoice</title>
<style>
  .clearfix:after {
  content: "";
  display: table;
  clear: both;
}

a {
  text-decoration: underline;
}

body {
  position: relative;
  margin: 0 auto; 
  color: #001028;
  background: #FFFFFF; 
  font-family: Arial, sans-serif; 
  font-size: 14px; 
  font-family: Arial;
}

header {
  padding: 10px 0;
  margin-bottom: 30px;
}

#logo {
  text-align: center;
  margin-bottom: 10px;
}

#logo img {
  width: 90px;
}

h1 {
  
  color: #5D6975;
  font-size: 2.4em;
  line-height: 1.4em;
  font-weight: normal;
  text-align: center;
  margin: 0 0 20px 0;
}

#project {
  float: left;
}

#project span {
  color: #5D6975;
  text-align: right;
  width: 52px;
  margin-right: 10px;
  display: inline-block;
  font-size: 14px;
}

#company {
  float: right;
  text-align: right;
}

#project div,
#company div {
  white-space: nowrap;        
}

table {
  width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
  margin-bottom: 20px;
}



table th,
table td {
  text-align: center;
}

table th {
  
  
  color: #5D6975;
  border-bottom: 1px solid #C1CED9;
  white-space: nowrap;        
  font-weight: normal;
}

table .service,
table .desc {
  text-align: left;
}

table td {
 padding-top:5px;
 padding-bottom:5px;
  
}

table tr {
  border-bottom: 1px solid #C1CED9;
}

table td.service,
table td.desc {
  vertical-align: top;
}

table td.unit,
table td.qty,
table td.total {
  font-size: 1.2em;
}

table td.grand {
  border-top: 1px solid #5D6975;;
}

#notices .notice {
  color: #5D6975;
  font-size: 1.2em;
}

footer {
  color: #5D6975;
  width: 100%;
  height: 30px;
  position: absolute;
  bottom: 0;
  border-top: 1px solid #C1CED9;
  padding: 8px 0;
  text-align: center;
}


  </style>
</head>

   <body> 
   <section id="header-section">
       
    <table style="width: 100%; border 0px">
     <tr>
         <th style="text-aligne:left; width: 25%">
            <img src="media/{{object.profile.company_logo}}" height="100px">
         </th>
         <th stlye="text-aligne:right">
             <br>
             <div stlye="font-size:18px"><h1></h1></div>
             Completion date: {{ object.completion_date }}<br>
             Issue date: {{ object.issued_date }}<br>
             Payment date: {{ object.payement_date }}<br>
             Company Website {{object.clients.website}}<br>
            <div>Account number: {{ object.profile.account_number }}</div>
         </th>
         </tr>
             <h1 class="brand-name">Company: {{ object.profile.company_name }}</h1>
            </div>
            <h1>{{ object.invoice_number }}</h1>
            <div id="company" class="clearfix">
              <div>SELLER:{{ object.profile.company_name }}</div>
              <div>BANK NAME:  {{ object.profile.bank_name }}</div>
              <div>ACCOUNT.no:  {{ object.profile.account_number }}</div>
              <div>REGISTRATION no. {{ object.profile.company_reg_no }}</div>
            </div>
            <div id="project">
              <div><span>CLIENT:</span> {{ object.clients.name }}</div>
              <div><span>DATE:</span> {{object.completion_date}}</div>
              <div><span>INVOICE ID:</span> {{object.invoice_number}}</div>
              <div><span>ADDRESS:</span> {{ object.clients.client_address }}</div>
              <div><span>REGISTRATION no:</span> {{ object.clients.company_reg_no }}</div>
              <div><span>VAT no:</span> {{ object.clients.vat_no }}</div>
            </div>
            <br>
            <br>
            </table>
        </section>
        <br>
 
        <section id="data-section">
            {% if object.positions %}
            <h3>Positions</h3>
            <table style='width: 100%'> 
                <tr style="background-cole-color:#e8e8e8">
                    <th style="text-aligne:left; width:20%">#</th>
                    <th style="text-aligne:left">Title</th>
                    <th style="text-aligne:left" >Description</th>
                    <th style="text-aligne:left" >Quantity</th>
                    <th style="text-aligne:left" >Price</th>
                    <th style="text-aligne:left" >Subtotal</th>
                </tr>
                {% for position in object.positions %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>
                                 {{ position.title }}
                            </td>
                            <td>
                                {{ position.description  }}
                            </td>
                            <td>
                                 {{ position.quantity }}
                            </td>
                            <td>
                                R {{ position.price }}
                            </td>
                            <td>
                              R {% widthratio position.quantity 1 position.price %}
                          </td>
                        </tr>
                    {% endfor %}
                    </table>
                    {% else %}
                    <h3> No positions added </h3>
                     {% endif %}
                     <div style="font-size:15px; margin-top:10px; text-align:right">Total: R {{object.total_amount}}</div>
                </section>

</body>
</html>

templates/invoice/pdf_printori.html
<!doctype html>
<html>
<head>

<title>Troubleshooting</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
    page{
        size:a4 portait; 
        margin: 2cm;
    }

    font-face {
        font-family: 'Lato';
        src: url({{ static.font }});

    }
    * {
        font-family: 'Lato';
        font-size: 12px;
    }
     table {
         border-collapse: collapse;
         border: 1px solid #ea8e8e8;
         padding: 5px;
     }
    </style>
</head>
<body> 
<section id="header-section">
    
    <table style="width: 100%; border 0px">
     <tr>
         <th style="text-aligne:left; width: 25%">
             <img src="{{ static.zibi_logo }}" width="150">
         </th>
         <th stlye="text-aligne:right">
             <br>
             <div stlye="font-size:18px"Invoice number {{obj.number}}></div>
             Completion date: {{ object.completion_date }}<br>
             Issue date: {{ object.issue_date }}<br>
             Payment date: {{ obj.payment_date }}<br>
            <div>account number: {{ object.profile.account_number }}</div>
         </th>
         </tr>
         </table>
         <hr>
         <br>
         <table style="width: 100%">
             <th style="text-aligne:left">
                 <div stlye="font-size:15px">Seller</div>
                 {{ object.profile.company_name }}<br>
             </th>
             <th style="text-aligne:left">
                 <div style="font-size:18px">Client:</div>
                 {{ object.client.name }}<br>
                 {{ object.client.address  }}<br>
                 {{ object.address.website }}
             </th>
            </table>
        </section>
        <br>

        <section id="data-section">
            {% if object.positions %}
            <h3>Positions</h3>
            <table style='width: 100%'> 
                <tr style="background-cole-color:#e8e8e8">
                    <th style="text-aligne:left; width:5%">#</th>
                    <th style="text-aligne:left">Title</th>
                    <th style="text-aligne:left" >Description</th>
                    <th style="text-aligne:left" >Amount</th>
                </tr>
                {% for position in object.positions %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>
                                {{ position.title }}
                            </td>
                            <td>
                                {{ position.description  }}
                            </td>
                            <td>
                                R {{ position.amount }}
                            </td>
                        </tr>
                    {% endfor %}
                    </table>
                    {% else %}
                    <h3> No positions added </h3>
                     {% endif %}
                     <div style="font-size:15px; margin-top:10px; text-align:right">Total: R {{object.total_amount}}</div>
                </section>

</body>
</html>

templates/invoice/position_confirm_delete.html
{% extends 'partials/base.html' %}

{% block title %}

delete

{% endblock title %}


{% block  content %}
  <form action="" method="POST">
      {% csrf_token %}
       <p>
           Are you sure you want to delete ""<b>{{ object.title }}?</b>""
          <button types="submit" class="btn btn-danger" data-loading-text>Yes</button>
        </p>

{% endblock content %}

templates/invoice/update.html
{% extends 'partials/base.html' %}

{% load crispy_forms_tags %}

{% block title %}
  Update Invoice 
{% endblock title %}

{% block content %}
   <form action="" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
       <button type="submit" class="btn btn-primary ">Update</button>
  </form>
{% endblock content %}