estimates/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    EstimateListView,
    EstimateFormView,
    EstimateUpdateView,
    AddPositionsFormView,
    CloseEstimateView,
    EstimateDeleteView,
    EstimatePositionDeleteView,
    estimate_pdf_print,
)

app_name = 'estimates'

urlpatterns = [
    path('', login_required(EstimateListView.as_view()), name='main'),
    path('new/',login_required(EstimateFormView.as_view()), name="estimate"),
    path('<pk>/', login_required(AddPositionsFormView.as_view()), name='estimate_detail'),
    path('<pk>/close/', login_required(CloseEstimateView.as_view()), name='close'),
    path('<pk>/update/', login_required(EstimateUpdateView.as_view()), name='estimate-update'),
    path('<pk>/delete/', login_required(EstimateDeleteView.as_view()), name='estimate-delete'),
    path('<pk>/pdf/', login_required(estimate_pdf_print), name="pdf"),
    path('<pk>/delete/<int:position_pk>/', login_required(EstimatePositionDeleteView.as_view()), name='position-delete'),
]

invoice_app/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    InvoiceListView,
    InvoiceFormView,
    InvoiceUpdateView,
    InvoiceUpdateView,
    AddPositionsFormView,
    CloseInvoiceView,
    InvoiceDeleteView,
    InvoicePositionDeleteView,
    PayedInvoiceView,
    invoices_pdf_print,

    
)


app_name = 'invoice_app'

urlpatterns = [
    path('', login_required(InvoiceListView.as_view()), name='main'),
    path('new/', login_required(InvoiceFormView.as_view()), name="create"),
    path('<pk>/', login_required(AddPositionsFormView.as_view()), name='detail'),
    path('<pk>/close/', login_required(CloseInvoiceView.as_view()), name='close'),
    path('<pk>/payed/', login_required(PayedInvoiceView.as_view()), name='payed'),
    path('<pk>/update/', login_required(InvoiceUpdateView.as_view()), name='update'),
    path('<pk>/pdf/', login_required(invoices_pdf_print), name="pdf"),
    path('<pk>/delete/', login_required(InvoiceDeleteView.as_view()), name='invoice-delete'),
    path('<pk>/delete/<int:position_pk>/', login_required(InvoicePositionDeleteView.as_view()), name='position-delete'),
    
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from invoice_app .views import dashboard
from profiles.views import login_view
from estimates.views import EstimateFormView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='account_login'),
    path('',dashboard, name='profile_view'),
    path('positions/', include('positions.urls', namespace ='positions')),
    path('invoice_app/', include('invoice_app.urls', namespace ='invoice_app')),
    path('estimates/', include('estimates.urls', namespace ='estimates')),
    path('clients/', include('clients.urls', namespace='clients')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/',include('allauth.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls'))
]

urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Veedata Invoice panel"
admin.site.index_title = "Veedata Invoice Management"

positions/urls.py
from django.urls import path, include
from dash_apps.account import index
from django.contrib.auth.decorators import login_required
from .views import (
invoice_analytics,
analytics_routes,
InvoiceAnalyticView,
payed_invoice)

from dash_apps import (
invoice_plots,
payed_plot)
app_name = 'positions'

urlpatterns = [
    path('analytics/',login_required(invoice_analytics), name='invoice_plot'),
    path('plot/',login_required(InvoiceAnalyticView.as_view()), name='plot'),
    path('payed/',login_required(payed_invoice), name='payed'),
    path('pychart/', login_required(index), name='pychart'),
    path('routes/',login_required(analytics_routes), name='routing')
]

profiles/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
 CreateProfileView,
 ProfileUpdateView,
 ProfileDetailView,
 logout_view,
 signup_view,
)

app_name = 'profiles'

urlpatterns = [
    path('logout/', logout_view, name='account_logout'),
    path('signup/', signup_view, name='account_signup'),
    path('profilecreate/', login_required(CreateProfileView.as_view()), name='profile_create' ),
    path('profile/<str:username>',login_required(ProfileDetailView.as_view()), name='profile_detail'),
    path('profileupdate/<str:username>/',login_required(ProfileUpdateView.as_view()), name='profile_update')
]

templates/partials/base.html
 {% include 'partials/head.html' %}
  <body>
    {% include 'partials/navbar.html' %}
    
    {% block title %}
    
    {% endblock title %}
    
    <div class="container mt-3">
      {% block content %}
      
      
      {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    
  </body>
</html>

templates/partials/head.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

     <!-- style CSS -->
     <link rel="stylesheet" href="{% static 'style.css' %}">

     {% block scripts %}

     {% endblock scripts %}

    <title>Veedata invoice app | {% block title %}{% endblock title %} </title>
  </head>

templates/partials/navbar.html
            {% if user.is_authenticated %}
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
              <a href="{% url 'invoice_app:main' %}" class="navbar-brand">Veedata Invoice</a>
              <a href="{% url 'invoice_app:create' %}" class="btn btn-outline-light">+ Invoice</a>
              <a href="{% url 'estimates:estimate' %}" class="btn btn-outline-light">+ Quotation</a>
              <a href="{% url 'positions:routing' %}" class="btn btn-outline-light">Analytics</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                <ul class="navbar-nav">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                      <li><a class="dropdown-item" href="{% url 'profiles:profile_detail' request.user.username %}">Profile</a></li>
                      <li><a class="dropdown-item" href="{% url 'profiles:profile_update' request.user.username %}">Update profile</a></li>
                      <li><a class="dropdown-item" href="{% url 'profiles:account_logout' %}">Logout</a></li>
                      {% else %}
                      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                          <div class="container-fluid">
                           <li class="nav-item"><a href="{% url 'account_login' %}" class="btn btn-outline-light">SignIn</a></li>
                            <li class="nav-item"><a href="{% url 'account_signup' %}"class="btn btn-outline-light">SignUp</a></li>
                          </nav>      
                      </div>
                      {% endif %}
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>