main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from invoice_app .views import dashboard
from profiles.views import login_view
from estimates.views import EstimateFormView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='account_login'),
    path('',dashboard, name='profile_view'),
    path('positions/', include('positions.urls', namespace ='positions')),
    path('invoice_app/', include('invoice_app.urls', namespace ='invoice_app')),
    path('estimates/', include('estimates.urls', namespace ='estimates')),
    path('clients/', include('clients.urls', namespace='clients')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/',include('allauth.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls'))
]

urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Veedata Invoice panel"
admin.site.index_title = "Veedata Invoice Management"

positions/urls.py
from django.urls import path, include
from dash_apps.account import index
from django.contrib.auth.decorators import login_required
from .views import (
invoice_analytics,
analytics_routes,
InvoiceAnalyticView,
payed_invoice)

from dash_apps import (
invoice_plots,
payed_plot)
app_name = 'positions'

urlpatterns = [
    path('analytics/',login_required(invoice_analytics), name='invoice_plot'),
    path('plot/',login_required(InvoiceAnalyticView.as_view()), name='plot'),
    path('payed/',login_required(payed_invoice), name='payed'),
    path('pychart/', login_required(index), name='pychart'),
    path('routes/',login_required(analytics_routes), name='routing')
]

templates/dash_plots/analytic_routs.html
{% extends 'partials/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Analytic Routes</h1>
            <ol class="breadcrumb mb-4">
                </ol>
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-primary text-white mb-4">
                        <div class="card-body">Projected Earnings</div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" href=" {% url 'positions:invoice_plot' %} ">View Details</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-warning text-white mb-4">
                        <div class="card-body">Monthly Report</div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" href="{% url 'positions:pychart' %}">View Details</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-success text-white mb-4">
                        <div class="card-body">Realised Earnings</div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" href="#">View Details</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-danger text-white mb-4">
                        <div class="card-body">Unpayeed Invoices</div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" href="{% url 'positions:payed' %}">View Details</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header"><h1 class="text-center font-weight-light my-4">Login to Invoice App </h1></div>
                <div class="card-body">
            {% endif %}

            {% endblock content %}

templates/dash_plots/estimate_plots.html
{% extends 'partials/base.html' %}
{% load static %}

{% block title %}
<title>Veedata Invoice Analytics</title>
{% endblock title %}
<script src="{% static 'https://cdn.plot.ly/plotly-latest.min.js' %}"></script>
{% block content %}
    {% load plotly_dash %}
     <div class="row">
         <div class="col-xl-11">
             <div class="card mb-10">
                  <div class="card-header">
                      <i class="fas fa-chart-area mr-1"><h4>Payed Invoice</h4></i>
                           <div class="{% plotly_class name='invoice_bar' %} card" style="height: 100%; width: 100% ">
                        {% plotly_app name='invoice_bar' ratio=0.75  %}
              </div>
          </div>
       </div>


 {% endblock content %}

templates/dash_plots/invoice_plot.html
{% extends 'partials/base.html' %}
{% load static %}

{% block title %}
<title>Veedata Invoice Analytics</title>
{% endblock title %}
<script src="{% static 'https://cdn.plot.ly/plotly-latest.min.js' %}"></script>
{% block content %}
    {% load plotly_dash %}
     <div class="row">
         <div class="col-xl-11">
             <div class="card mb-10">
                  <div class="card-header">
                      <i class="fas fa-chart-area mr-1"><h4>Invoices</h4></i>
                           <div class="{% plotly_class name='invoice_bar' %} card" style="height: 100%; width: 100% ">
                        {% plotly_app name='invoice_bar' ratio=0.75  %}
              </div>
          </div>
       </div>


 {% endblock content %}

templates/dash_plots/payed_invoice.html
{% extends 'partials/base.html' %}
{% load static %}

{% block title %}
<title>Veedata Invoice Analytics</title>
{% endblock title %}
<script src="{% static 'https://cdn.plot.ly/plotly-latest.min.js' %}"></script>
{% block content %}
    {% load plotly_dash %}
     <div class="row">
         <div class="col-xl-11">
             <div class="card mb-10">
                  <div class="card-header">
                      <i class="fas fa-chart-area mr-1"><h4>Invoices</h4></i>
                           <div class="{% plotly_class name='payed_bar' %} card" style="height: 100%; width: 100% ">
                        {% plotly_app name='payed_bar' ratio=0.75  %}
              </div>
          </div>
       </div>


 {% endblock content %}

templates/dash_plots/pycharts.html
{% include "partials/head.html" %}
<html>
{% include 'partials/navbar.html' %}

<head>
    <meta charset="utf-8">
    <title>The Invoice calendar</title>
    {% for jsfile_name in script_list %}
    <script src="{{host}}/{{jsfile_name}}.js"></script>
    {% endfor %}
</head>

<body>
  {{myechart|safe}}
  {{ calchart |safe }}
</body>

</html>