clients/urls.py
from .views import CreateClientView
from django.urls import path

app_name = 'clients'

urlpatterns = [
   path('createclient/', CreateClientView.as_view(), name='client_create'),
]

estimates/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    EstimateListView,
    EstimateFormView,
    EstimateUpdateView,
    AddPositionsFormView,
    CloseEstimateView,
    EstimateDeleteView,
    EstimatePositionDeleteView,
    estimate_pdf_print,
)

app_name = 'estimates'

urlpatterns = [
    path('', login_required(EstimateListView.as_view()), name='main'),
    path('new/',login_required(EstimateFormView.as_view()), name="estimate"),
    path('<pk>/', login_required(AddPositionsFormView.as_view()), name='estimate_detail'),
    path('<pk>/close/', login_required(CloseEstimateView.as_view()), name='close'),
    path('<pk>/update/', login_required(EstimateUpdateView.as_view()), name='estimate-update'),
    path('<pk>/delete/', login_required(EstimateDeleteView.as_view()), name='estimate-delete'),
    path('<pk>/pdf/', login_required(estimate_pdf_print), name="pdf"),
    path('<pk>/delete/<int:position_pk>/', login_required(EstimatePositionDeleteView.as_view()), name='position-delete'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from invoice_app .views import dashboard
from profiles.views import login_view
from estimates.views import EstimateFormView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='account_login'),
    path('',dashboard, name='profile_view'),
    path('positions/', include('positions.urls', namespace ='positions')),
    path('invoice_app/', include('invoice_app.urls', namespace ='invoice_app')),
    path('estimates/', include('estimates.urls', namespace ='estimates')),
    path('clients/', include('clients.urls', namespace='clients')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/',include('allauth.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls'))
]

urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Veedata Invoice panel"
admin.site.index_title = "Veedata Invoice Management"

estimates/models.py
from decimal import Decimal
from django.db.models import F, Sum
from django.db import models
import profile
from django.db import models
from clients.models import Client
from profiles.models import Profiles 

class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)

class Estimate(models.Model):
    profile = models.ForeignKey(Profiles, on_delete=models.CASCADE)
    clients = models.ForeignKey(Client, on_delete=models.CASCADE)
    estimate_number = models.CharField(max_length=100)
    completion_date = models.DateField(null=True, blank=True)
    issued_date = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    closed = models.BooleanField(default=False)
    payed= models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, blank=True)
    
    def __str__(self):
        return f"Invoice; {self.invoice.estimate_number}, postion title: {self.title}"
    

    def __str__(self):
        return f"Invoice number: {self.estimate_number}, pk: {self.pk}"
  
    @property
    def tags(self):
        return self.tags.all()

    @property
    def positions(self):
        return self.position_set.all()

    @property
    def total_amount(self):
        return self.positions.aggregate(
            total_price=Sum(F('quantity') * F('price'))
        )['total_price'] or Decimal('0')
        

estimates/forms.py
from django import forms
from .models import Estimate
from django.core.exceptions import ValidationError

class EstimateForm(forms.ModelForm):
    completion_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label='Completion date'  )
    issue_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label='Date of Issue')
    
    class Meta:
        model = Estimate
        fields = (
            'clients', 
            'estimate_number', 
            'completion_date', 
            'issue_date',
        )

        label = {
            'estimate_number':'Quotation No.',
        }

    def clean_number(self):
        number = self.cleaned_data.get('estimate_number')
        if len(number) < 10:
            raise ValidationError('Number is too short')
        return number

estimates/views.py
from xml.parsers.expat import model
from django.shortcuts import render, redirect
from positions.models import Position
from profiles.models import Profiles
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from.models import Estimate
from.forms import EstimateForm
from estipositions.forms import EstimatePositionForm
from django.contrib import messages
from.mixins import EstimateNoteClosedMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders
from django.views.generic import (
    ListView,
    FormView,  
    DetailView,
    UpdateView, 
    RedirectView, 
    DeleteView
)


class EstimateListView(ListView):
    model =Estimate
    template_name ="estimates/estimate_index.html"
    paginate_by = 3
    context_object_name = 'qs'
    

    def get_queryset(self):
        profile = get_object_or_404(Profiles, user=self.request.user)
        return super().get_queryset().filter(profile=profile).order_by('-created')

class EstimateFormView(FormView):
    form_class = EstimateForm
    template_name = 'estimates/create_estimate.html'
    i_instance = None

    def get_success_url(self):
        return reverse('estimates:estimate_detail', kwargs={'pk':self.i_instance.pk})

    def form_valid(self, form):
        profile = Profiles.objects.get(user=self.request.user)
        instance = form.save(commit=False)
        instance.profile = profile
        form.save()
        self.i_instance = instance
        return super().form_valid(form)

class EstimateDeleteView(DeleteView):
    
    model = Estimate
    success_url = reverse_lazy('estimates:main')
    template_name = 'invoice/invoice_confirm_delete.html'

    def in_delete(request,self,id):
        estimate = Estimate.get_object_or_404(Estimate, id=id)
        estimate.delete()
        #messages.info(self.request, f'Delete position, - {self.object.invoice_number}')
        return redirect(reverse("estimates:main"))


class AddPositionsFormView(FormView):
    form_class = EstimatePositionForm
    template_name = 'estimates/detail.html'

    def get_success_url(self):
        return self.request.path
    
    def form_valid(self, form):
        estimate_pk = self.kwargs.get('pk')
        estimate_obj = Estimate.objects.get(pk=estimate_pk)
        instance = form.save(commit=False)
        instance.estimate = estimate_obj
        form.save()
        messages.info(self.request, f'Successfully added position- {instance.title}')
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        estimate_obj = Estimate.objects.get(pk=self.kwargs.get('pk'))
        qs = estimate_obj.positions
        context['obj'] = estimate_obj
        context['qs'] = qs
        return context

class EstimateUpdateView(LoginRequiredMixin, EstimateNoteClosedMixin, UpdateView):
    model = Estimate
    template_name = 'estimates/update.html'
    form_class = EstimateForm
    success_url = reverse_lazy('estimates:main')

    def form_valid(self, form):
        instance = form.save()
        messages.info(self.request, f'Successfuly updated estimate - {instance.estimate_number}')
        return super().form_valid(form)


class CloseEstimateView(RedirectView ):
    
    pattern_name =  "estimates:estimate_detail"

    def get_redirect_url(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Estimate.objects.get(pk=pk)
        obj.closed = True
        obj.save()
        return super().get_redirect_url(*args, **kwargs)

class EstimatePositionDeleteView(EstimateNoteClosedMixin, DeleteView):
    model = Position
    template_name = 'estimate/position_confirm_delete.html'

    def get_object(self):
        pk = self.kwargs.get('position_pk')
        obj = Position.objects.get(pk=pk)
        return obj

    def get_success_url(self):
        messages.info(self.request, f'Delete position, - {self.object.title}')
        return reverse('estimate:detail', kwargs={'pk':self.object.estimtae.id})


def estimate_pdf_print(request, **kwargs):
    pk = kwargs.get('pk')
    obj = Estimate.objects.get(pk=pk)

    logo_result =finders.find('img/zibi_logo.png')
    font_result = finders.find('fonts/Lato-Regular.ttf')
    searched_locations = finders.searched_locations
    print(searched_locations)

    template_path =  'estimates/pdf_print.html'
    
    context = {
        'object': obj,
        'static': {
            'font': font_result,
            'logo': logo_result,
        },
    }

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="estimate.pdf"'

    template = get_template(template_path)
    html = template.render(context)

    pisa_status = pisa.CreatePDF(
       html.encode('utf-8'), dest=response, encoding='utf-8')

    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

templates/estimates/create_estimate.html
{% extends 'partials/base.html' %}

{% block title %}
<div class="col-md-6 text-centered">
  <h3>create a new Quotation</h3>
</div>
{% endblock title %}

{% load crispy_forms_tags %}
{% block content %}
    <a href="{% url 'clients:client_create' %}" class ="btn btn-warning"> +add client</a>
    <a href=" {% url 'estimates:main' %}" class ="btn btn-success">list of Quotations</a>
   <form action="" method="POST">
        {% csrf_token %}
        {{ form| crispy }}
       <button type="submit" class="btn btn-primary ">save</button>
  </form>
{% endblock content %}

templates/estimates/detail.html
{% extends 'partials/base.html' %}

{% load crispy_forms_tags %}

{% block title %}

{% endblock title %} 

{% block content %}

 
     <!--add Modal -->
    <div class="modal fade" id="addPositionsModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">add position</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
             <form action="" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <div class="modal-footer">
                  <button type="submit"  class="btn btn-secondary" value="Submit">Save changes</button>
              </form>
          </div>
          </div>
        </div>
      </div>
      </div>
      
       <!--Estimate Modal -->
       <div class="modal fade" id="closePositionsModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="staticBackdropLabel">Caution</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body">
                 Are you sure you want to close the Quotation ?
                 <p>When Quotation is closed it will not be edited.</p>
               </div>
               <div class="modal-footer">
              <a href="{% url 'estimates:close' obj.pk %}" class="btn btn-secondary">Close</a>
             </div>
           </div>
          </div>
        </div>
      <div>
        {% if not obj.closed  %}
        <!-- Button trigger modal -->
       <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addPositionsModal">
        +add position.
       </button>
       <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#closePositionsModal">
        close positions.
       </button>
      
      </div>    
        {% else %}
        <a href="{% url 'estimates:pdf' obj.pk %}" class ="btn btn-danger">export pdf</a>
        {% endif %}
    
    {% if messages %}
     {% for message in messages %}
       {% if message.tags == 'info' %}
          <div class ="alert alert-primary mt-2">
           {{message}}
        {% endif %} 
      {% endfor %}
    {% endif %}
 

   <div class= "mt-3">
      <h5>Client : {{obj.client.name}}</h5>
      <hr>
      <h3>Positions</h3> {{obj.client.name}}</h3>
   
      {% if qs %}
      <table class="table">
        <thead>
          <tr>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Description</th>
              <th scope="col">Qty</th>
              <th scope="col">Price</th>
              <th scope="col">Subtotal</th>
              <th scope="col">Delete</th>
           </tr>
        </thead>
        <tbody>
          {% for item in qs %}
            <tr style = "vertical-align:middle;">
                <th scope="row">{{forloop.counter}}</th>
                <td>{{item.title}}</td>
                <td>{{item.description}}</td>
                <td>{{item.quantity}}</td>
                <td>R {{item.price}}</td>
                <td>R {% widthratio item.quantity 1 item.price %}</td>
                <td>
                    {% if not obj.closed %}
                    <a href="{% url 'invoice_app:position-delete' obj.pk item.pk %}" class="btn btn-danger">x</a>
                    {% else %}
                    closed
                    {% endif %}
                  </td>
          
             </tr>
            {% endfor %}
            
           </tbody>
        </table> 
        <div class="mt-2 text-end">
            <h2>Total amount: R {{ obj.total_amount}}</h2>
        </div>
        {% else %}

        <h5>No positions yet.</h>
        {% endif %}


   </div>
{% endblock content %}

templates/estimates/estimate_index.html
 {% extends "partials/base.html" %}

 {% block title %}


 {% endblock title %}


 {% block content %}

  {% if messages %}
     {% for message in messages %}
       {% if message.tags == 'info' %}
        <div class ="alert alert-primary mt-2">
           {{message}}
        {% endif %} 
      {% endfor %}
     {% endif %}
      
   {% if qs %}
      {% for obj in qs %}
     <div class="card mb-2" style="width:100">
       <div class="card-body">
         <h5 class="card-title">{{ obj.estimate_number}} - {{obj.client.name}}</h5>
         <div class="card-text">completion date: {{obj.completion_date}}</div>
         <div class="text-muted">Amount in R{{obj.total_amount}}</div>
         <div class="mt-2">
            <a href="  {% url 'estimates:estimate_detail' obj.pk %} "class="btn btn-primary">Details</a>
             {% if not obj.closed %}
             <a href="  {% url 'estimates:estimate-delete' obj.pk%} "class="btn btn-danger">Delete</a>
            <a href="  {% url 'estimates:estimate-update' obj.pk %} "class="btn btn-info">Update</a>
            {% endif %}
        </div>
      </div>
    <div>{% if page_obj.has_previous %}
     {% endif %}
     {% endfor %}
     {% else %}
      <h3> No Quotation created. </h3>
    
      {% endif %}
      {% if is_paginated %}
      <nav aria-label="estimate pagination">
        <ul class="pagination">
          <li class="page-item{% if page.obj.has_previous %} {% else %} enabled {% endif %}">
            <a {% if page_obj.has_previous %}
            href="?page={{page_obj.previous_page_number}}"
          {% endif %} class="page-link" >Previous</a>
          </li>
          {% for i in paginator.page_range  %}
          <li class="page-item {% if page_obj.number == i %} active{% endif %}">
             <a class="page-link" href="?page={{i}}">{{i}}</a>
            </li>
          {% endfor %}
          <li class="page-item{% if page.obj.has_next %} {% else %} enabled {% endif %}">
            <a {% if page_obj.has_next %}
            href="?page={{page_obj.next_page_number}}"
          {% endif %} class="page-link" >Next</a>
          </li>
        </ul>
      </nav>
      
      {% endif %}


 {% endblock content %}

templates/estimates/pdf_print.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <title>Quotation</title>
<style>
  .clearfix:after {
  content: "";
  display: table;
  clear: both;
}

a {
  text-decoration: underline;
}

body {
  position: relative;
  margin: 0 auto; 
  color: #001028;
  background: #FFFFFF; 
  font-family: Arial, sans-serif; 
  font-size: 14px; 
  font-family: Arial;
}

header {
  padding: 10px 0;
  margin-bottom: 30px;
}

#logo {
  text-align: center;
  margin-bottom: 10px;
}

#logo img {
  width: 90px;
}

h1 {
  
  color: #5D6975;
  font-size: 2.4em;
  line-height: 1.4em;
  font-weight: normal;
  text-align: center;
  margin: 0 0 20px 0;
}

#project {
  float: left;
}

#project span {
  color: #5D6975;
  text-align: right;
  width: 52px;
  margin-right: 10px;
  display: inline-block;
  font-size: 14px;
}

#company {
  float: right;
  text-align: right;
}

#project div,
#company div {
  white-space: nowrap;        
}

table {
  width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
  margin-bottom: 20px;
}



table th,
table td {
  text-align: center;
}

table th {
  
  
  color: #5D6975;
  border-bottom: 1px solid #C1CED9;
  white-space: nowrap;        
  font-weight: normal;
}

table .service,
table .desc {
  text-align: left;
}

table td {
 padding-top:5px;
 padding-bottom:5px;
  
}

table tr {
  border-bottom: 1px solid #C1CED9;
}

table td.service,
table td.desc {
  vertical-align: top;
}

table td.unit,
table td.qty,
table td.total {
  font-size: 1.2em;
}

table td.grand {
  border-top: 1px solid #5D6975;;
}

#notices .notice {
  color: #5D6975;
  font-size: 1.2em;
}

footer {
  color: #5D6975;
  width: 100%;
  height: 30px;
  position: absolute;
  bottom: 0;
  border-top: 1px solid #C1CED9;
  padding: 8px 0;
  text-align: center;
}


    </style>
</head>
<body> 
    <section id="header-section">
       
        <table style="width: 100%; border 0px">
         <tr>
             <th style="text-aligne:left; width: 25%">
                <img src="media/{{object.profile.company_logo}}" height="2000px">
             </th>
             <th stlye="text-aligne:right">
                 <br>
                 <div stlye="font-size:18px"><h1></h1></div>
                 Completion date: {{ object.completion_date }}<br>
                 Issue date: {{ object.issued_date }}<br>
                 Payment date: {{ object.payement_date }}<br>
                 Company Website {{object.clients.website}}<br>
                <div>Account number: {{ object.profile.account_number }}</div>
             </th>
             </tr>
                 <h1 class="brand-name">Company: {{ object.profile.company_name }}</h1>
                </div>
                <h1>{{ object.invoice_number }}</h1>
                <div id="company" class="clearfix">
                  <div>SELLER:{{ object.profile.company_name }}</div>
                  <div>ACCOUNT.no:  {{ object.profile.account_number }}</div>
                  <div>REGISTRATION no. {{ object.profile.company_reg_no }}</div>
                </div>
                <div id="project">
                  <div><span>CLIENT:</span> {{ object.clients.name }}</div>
                  <div><span>DATE:</span> {{object.completion_date}}</div>
                  <div><span>QUOTATION ID:</span> {{object.estimate_number}}</div>
                  <div><span>ADDRESS:</span> {{ object.clients.client_address }}</div>
                  <div><span>REGISTRATION no:</span> {{ object.clients.company_reg_no }}</div>
                  <div><span>VAT no:</span> {{ object.clients.vat_no }}</div>
                </div>
                <br>
                <br>
                </table>
        </section>
        <br>

        <section id="data-section">
            {% if object.positions %}
            <h3>Positions</h3>
            <table style='width: 100%'> 
                <tr style="background-cole-color:#e8e8e8">
                    <th style="text-aligne:left; width:5%">#</th>
                    <th style="text-aligne:left">Title</th>
                    <th style="text-aligne:left" >Description</th>
                    <th style="text-aligne:left" >quantity</th>
                    <th style="text-aligne:left" >price</th>
                </tr>
                {% for position in object.positions %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>
                                {{ position.title }}
                            </td>
                            <td>
                                {{ position.description  }}
                            </td>
                            <td>
                                 {{ position.quantity }}
                            </td><td>
                                R {{ position.price }}
                            </td>
                        </tr>
                    {% endfor %}
                    </table>
                    {% else %}
                    <h3> No positions added </h3>
                     {% endif %}
                     <div style="font-size:15px; margin-top:10px; text-align:right">Total: R {{object.total_amount}}</div>
                </section>

</body>
</html>

templates/estimates/position_confirm_delete.html
{% extends 'partials/base.html' %}

{% block title %}

delete

{% endblock title %}


{% block  content %}
  <form action="" method="POST">
      {% csrf_token %}
       <p>
           Are you sure you want to delete ""<b>{{ object.title }}?</b>""
          <button types="submit" class="btn btn-danger" data-loading-text>Yes</button>
        </p>

{% endblock content %}

templates/estimates/update.html
{% extends 'partials/base.html' %}

{% load crispy_forms_tags %}

{% block title %}
  <h1>Update Quotation</h3> 
{% endblock title %}

{% block content %}
   <form action="" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
       <button type="submit" class="btn btn-primary ">Update</button>
  </form>
{% endblock content %}